// All player-visible strings. Switching language is a data change only.
export const STR = {
  fr: {
    title: "OSTIA MONSTERS",
    subtitle: "La région d'Ostia t'attend",
    play: "JOUER",
    continue: "CONTINUER",
    options: "OPTIONS",
    back: "RETOUR",
    optMusic: "Musique",
    optSfx: "Effets sonores",
    optLang: "Langue",
    optQuality: "Qualité graphique",
    optQualityHigh: "Élevée",
    optQualityLow: "Basse",
    optFx: "Secousses d'écran",
    optOn: "Activé",
    optOff: "Désactivé",
    pause: "PAUSE",
    resume: "REPRENDRE",
    quitToMenu: "MENU PRINCIPAL",
    confirmQuit: "Quitter la partie ? La progression est sauvegardée aux centres de soins.",
    yes: "OUI",
    no: "NON",
    interact: "Parler / Agir",
    orbs: "Orbes",
    potions: "Potions",
    dex: "Ostiadex",
    lvl: "N.",
    hp: "PV",
    townSydnera: "Sydnera",
    townMelbora: "Melbora",
    townCanberry: "Canberry",
    route1: "Route 1 — Sentier des Eucalyptus",
    route2: "Route 2 — Piste Rouge",
    profName: "Professeur Eucalypt",
    matildaName: "Dresseuse Matilda",
    jackName: "Ranger Jack",
    healerName: "Infirmière Sheila",
    villagerName: "Habitant",
    profIntro1: "Bienvenue à Ostia, jeune dresseur ! Je suis le Professeur Eucalypt.",
    profIntro2: "Trois créatures sauvages de notre région ont accepté d'accompagner un débutant. Choisis bien !",
    profChoose: "Choisis ta première créature :",
    profGave: "Excellent choix ! Prends aussi 8 Orbes Capture et 3 Potions.",
    profTip: "Marche dans les hautes herbes pour rencontrer des créatures. Affaiblis-les, puis lance un Orbe pour les capturer !",
    profAfter: "Va voir la Dresseuse Matilda sur la Route 2, puis défie le Ranger Jack à Canberry !",
    starterConfirm: "Prendre {name} ?",
    villagerTip: "Les hautes herbes au nord grouillent de créatures. L'Ostiadex en compte 6 espèces !",
    healerHeal: "Bienvenue au centre de soins ! Tes créatures sont soignées et ta partie est sauvegardée.",
    matildaBefore: "G'day ! Je suis Matilda. Mes créatures et moi, on ne perd jamais. Un petit duel ?",
    matildaLost: "Waouh, bien joué ! Tiens, 5 Orbes Capture. Le Ranger Jack t'attend à Canberry, au nord.",
    matildaAfter: "Fonce à Canberry défier le Ranger Jack !",
    jackBefore: "Alors c'est toi qu'on entend arriver depuis Sydnera ? Je suis Jack, Ranger en chef d'Ostia. Montre-moi ta valeur !",
    jackLost: "Incroyable... Tu es désormais Champion de la région d'Ostia !",
    jackAfter: "Champion ! Continue d'explorer et complète ton Ostiadex.",
    battleWild: "Un {name} sauvage apparaît !",
    battleTrainer: "{name} veut se battre !",
    battleSend: "{name} envoie {mon} !",
    battleGo: "À toi, {mon} !",
    actAttack: "ATTAQUE",
    actCatch: "CAPTURER",
    actPotion: "POTION ({n})",
    actFlee: "FUIR",
    actSwitch: "CHANGER",
    usedMove: "{mon} utilise {move} !",
    superEffective: "C'est super efficace !",
    notEffective: "Ce n'est pas très efficace...",
    fainted: "{mon} est K.O. !",
    gainedXp: "{mon} gagne {n} XP.",
    levelUp: "{mon} passe au niveau {n} !",
    learnedMove: "{mon} apprend {move} !",
    threwOrb: "Tu lances un Orbe Capture...",
    caught: "Et hop ! {name} est capturé !",
    caughtFull: "{name} est capturé et envoyé au ranch du Professeur !",
    brokeFree: "Oh non, il s'est libéré !",
    noOrbs: "Tu n'as plus d'Orbes Capture !",
    cantCatchTrainer: "On ne capture pas la créature d'un dresseur !",
    usedPotion: "{mon} récupère {n} PV.",
    noPotions: "Tu n'as plus de Potions !",
    hpFull: "Les PV sont déjà au maximum !",
    fled: "Tu prends la fuite !",
    cantFlee: "Impossible de fuir un duel de dresseur !",
    trainerNext: "{name} envoie {mon} !",
    playerWon: "Tu remportes le duel !",
    playerLost: "Tu n'as plus de créature valide... Tu te précipites au centre de soins le plus proche.",
    victoryTitle: "CHAMPION D'OSTIA !",
    victoryBody: "Tu as vaincu le Ranger Jack. La région d'Ostia salue son nouveau champion !",
    victoryDex: "Ostiadex : {n} / 6 espèces",
    victoryContinue: "CONTINUER L'AVENTURE",
    chooseNext: "Quelle créature envoyer ?",
    typeFeu: "Feu",
    typePlante: "Plante",
    typeEau: "Eau",
    typeNormal: "Normal",
    newGameOverwrite: "Une sauvegarde existe. Commencer une nouvelle partie l'effacera. Continuer ?",
    saved: "Partie sauvegardée.",
    loading: "Chargement d'Ostia...",
    creditsNote: "Jeu fan non-officiel inspiré de Pokémon — créatures originales.",
  },
  en: {
    title: "OSTIA MONSTERS",
    subtitle: "The Ostia region awaits",
    play: "PLAY",
    continue: "CONTINUE",
    options: "OPTIONS",
    back: "BACK",
    optMusic: "Music",
    optSfx: "Sound effects",
    optLang: "Language",
    optQuality: "Graphics quality",
    optQualityHigh: "High",
    optQualityLow: "Low",
    optFx: "Screen shake",
    optOn: "On",
    optOff: "Off",
    pause: "PAUSED",
    resume: "RESUME",
    quitToMenu: "MAIN MENU",
    confirmQuit: "Quit the game? Progress is saved at heal centers.",
    yes: "YES",
    no: "NO",
    interact: "Talk / Act",
    orbs: "Orbs",
    potions: "Potions",
    dex: "Ostiadex",
    lvl: "Lv.",
    hp: "HP",
    townSydnera: "Sydnera",
    townMelbora: "Melbora",
    townCanberry: "Canberry",
    route1: "Route 1 — Eucalyptus Trail",
    route2: "Route 2 — Red Track",
    profName: "Professor Eucalypt",
    matildaName: "Trainer Matilda",
    jackName: "Ranger Jack",
    healerName: "Nurse Sheila",
    villagerName: "Villager",
    profIntro1: "Welcome to Ostia, young trainer! I am Professor Eucalypt.",
    profIntro2: "Three wild creatures of our region agreed to join a beginner. Choose wisely!",
    profChoose: "Choose your first creature:",
    profGave: "Excellent choice! Take 8 Capture Orbs and 3 Potions as well.",
    profTip: "Walk in tall grass to meet creatures. Weaken them, then throw an Orb to catch them!",
    profAfter: "Go meet Trainer Matilda on Route 2, then challenge Ranger Jack in Canberry!",
    starterConfirm: "Take {name}?",
    villagerTip: "The tall grass up north is full of creatures. The Ostiadex lists 6 species!",
    healerHeal: "Welcome to the heal center! Your creatures are healed and your game is saved.",
    matildaBefore: "G'day! I'm Matilda. My creatures and I never lose. Fancy a duel?",
    matildaLost: "Wow, well played! Here, 5 Capture Orbs. Ranger Jack awaits you in Canberry, up north.",
    matildaAfter: "Rush to Canberry and challenge Ranger Jack!",
    jackBefore: "So you're the one we've been hearing about since Sydnera? I'm Jack, head Ranger of Ostia. Show me your worth!",
    jackLost: "Unbelievable... You are now Champion of the Ostia region!",
    jackAfter: "Champion! Keep exploring and complete your Ostiadex.",
    battleWild: "A wild {name} appears!",
    battleTrainer: "{name} wants to battle!",
    battleSend: "{name} sends out {mon}!",
    battleGo: "Go, {mon}!",
    actAttack: "FIGHT",
    actCatch: "CATCH",
    actPotion: "POTION ({n})",
    actFlee: "RUN",
    actSwitch: "SWITCH",
    usedMove: "{mon} used {move}!",
    superEffective: "It's super effective!",
    notEffective: "It's not very effective...",
    fainted: "{mon} fainted!",
    gainedXp: "{mon} gained {n} XP.",
    levelUp: "{mon} grew to level {n}!",
    learnedMove: "{mon} learned {move}!",
    threwOrb: "You throw a Capture Orb...",
    caught: "Gotcha! {name} was caught!",
    caughtFull: "{name} was caught and sent to the Professor's ranch!",
    brokeFree: "Oh no, it broke free!",
    noOrbs: "You're out of Capture Orbs!",
    cantCatchTrainer: "You can't catch a trainer's creature!",
    usedPotion: "{mon} recovered {n} HP.",
    noPotions: "You're out of Potions!",
    hpFull: "HP is already full!",
    fled: "You fled the battle!",
    cantFlee: "You can't flee a trainer duel!",
    trainerNext: "{name} sends out {mon}!",
    playerWon: "You won the duel!",
    playerLost: "You have no healthy creature left... You rush to the nearest heal center.",
    victoryTitle: "CHAMPION OF OSTIA!",
    victoryBody: "You defeated Ranger Jack. The Ostia region salutes its new champion!",
    victoryDex: "Ostiadex: {n} / 6 species",
    victoryContinue: "CONTINUE ADVENTURE",
    chooseNext: "Which creature next?",
    typeFeu: "Fire",
    typePlante: "Plant",
    typeEau: "Water",
    typeNormal: "Normal",
    newGameOverwrite: "A save exists. Starting a new game will erase it. Continue?",
    saved: "Game saved.",
    loading: "Loading Ostia...",
    creditsNote: "Unofficial fan game inspired by Pokémon — original creatures.",
  },
};
